name: yolo
channels:
  - pytorch
  - nvidia
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=41.0.3
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.4.4
  - ffmpeg=4.3
  - filelock=3.9.0
  - flask=2.2.2
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - intel-openmp=2021.4.0
  - itsdangerous=2.0.1
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.7.2.10
  - libcurand=10.3.3.141
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.15
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - networkx=3.1
  - numexpr=2.8.1
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1w
  - pandas=1.4.2
  - pcre=8.45
  - pillow=8.4.0
  - pip=23.3
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyyaml=6.0
  - qt=5.9.7
  - readline=8.1
  - requests=2.31.0
  - seaborn=0.12.2
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - sympy=1.11.1
  - tk=8.6.11
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.1
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.16
  - werkzeug=2.2.3
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.11.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
      - argon2-cffi==21.1.0
      - attrs==21.2.0
      - backcall==0.2.0
      - bleach==4.1.0
      - debugpy==1.5.1
      - decorator==5.1.0
      - defusedxml==0.7.1
      - entrypoints==0.3
      - ipykernel==6.5.0
      - ipython==7.29.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.6.5
      - jedi==0.18.0
      - jinja2==3.0.3
      - jsonschema==4.2.1
      - jupyter==1.0.0
      - jupyter-client==7.0.6
      - jupyter-console==6.4.0
      - jupyter-core==4.9.1
      - jupyterlab-pygments==0.1.2
      - jupyterlab-widgets==1.0.2
      - kiwisolver==1.3.2
      - markupsafe==2.0.1
      - matplotlib==3.4.3
      - matplotlib-inline==0.1.3
      - mistune==0.8.4
      - nbclient==0.5.5
      - nbconvert==6.2.0
      - nbformat==5.1.3
      - nest-asyncio==1.5.1
      - notebook==6.4.5
      - numpy==1.26.1
      - opencv-python==4.5.5.62
      - packaging==21.2
      - pandocfilters==1.5.0
      - parso==0.8.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - prometheus-client==0.12.0
      - prompt-toolkit==3.0.22
      - protobuf==3.19.1
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pygments==2.10.0
      - pyparsing==2.4.7
      - pyrsistent==0.18.0
      - pyzmq==22.3.0
      - qtconsole==5.2.0
      - qtpy==1.11.2
      - scipy==1.11.3
      - send2trash==1.8.0
      - tensorboardx==2.4
      - terminado==0.12.1
      - testpath==0.5.0
      - tqdm==4.66.1
      - traitlets==5.1.1
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - widgetsnbextension==3.5.2
